/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ContactBlock = {
  _type: "contactBlock";
  marker?: string;
};

export type FormSubmission = {
  _id: string;
  _type: "formSubmission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  inquiryType?: string;
  name?: string;
  email?: string;
  hearAboutUs?: string;
  message?: string;
  submittedAt?: string;
};

export type StatsSection = {
  _type: "statsSection";
  theme?: "light" | "dark" | "primary" | "secondary";
  eyebrow?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }>;
};

export type MediaSection = {
  _type: "mediaSection";
  theme?: "light" | "dark" | "primary" | "secondary";
  eyebrow?: string;
  layout?: "fullBleed16x9" | "pairedSquare" | "textAndMedia";
  media?: Array<{
    _key: string;
  } & MuxVideo | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type TextSection = {
  _type: "textSection";
  theme?: "light" | "dark" | "primary" | "secondary";
  eyebrow?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type HighlightsSection = {
  _type: "highlightsSection";
  theme?: "light" | "dark" | "primary" | "secondary";
  eyebrow?: string;
  statement?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }>;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sections?: Array<{
    _key: string;
  } & HeroBlock | {
    _key: string;
  } & CapesBlock | {
    _key: string;
  } & ContactBlock>;
};

export type CapesBlock = {
  _type: "capesBlock";
  headline?: string;
  capabilities?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "capability";
  }>;
};

export type HeroBlock = {
  _type: "heroBlock";
  heading?: string;
  subheading?: string;
  video?: MuxVideo;
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "mux.videoAsset";
  };
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  client?: string;
  summary?: string;
  capabilities?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "capability";
  }>;
  heroVideo?: MuxVideo;
  year?: string;
  industry?: string;
  deliverables?: string;
  creativeCollective?: string;
  primaryColor?: string;
  secondaryColor?: string;
  body?: Array<{
    _key: string;
  } & HighlightsSection | {
    _key: string;
  } & TextSection | {
    _key: string;
  } & MediaSection | {
    _key: string;
  } & StatsSection>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Capability = {
  _id: string;
  _type: "capability";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  subtitle?: string;
  video?: MuxVideo;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<{
    _key: string;
  } & MuxTrack>;
  playback_ids?: Array<{
    _key: string;
  } & MuxPlaybackId>;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<{
    _key: string;
  } & MuxStaticRenditionFile>;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ContactBlock | FormSubmission | StatsSection | MediaSection | TextSection | HighlightsSection | Homepage | CapesBlock | HeroBlock | MuxVideo | CaseStudy | SanityImageCrop | SanityImageHotspot | Slug | Capability | MuxVideoAsset | MuxAssetData | MuxStaticRenditions | MuxStaticRenditionFile | MuxPlaybackId | MuxTrack | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../web/src/lib/queries.ts
// Variable: homepageQuery
// Query: *[_type == "homepage"][0]{    sections[]{      _type,      _type == "heroBlock" => {        heading,        subheading,        "videoPlaybackId": video.asset->playbackId      },      _type == "capesBlock" => {        headline,        capabilities[]->{          title,          "slug": slug.current,          "videoPlaybackId": video.asset->playbackId        }      },      _type == "contactBlock" => {        _type      }    }  }
export type HomepageQueryResult = {
  sections: Array<{
    _type: "capesBlock";
    headline: string | null;
    capabilities: Array<{
      title: string | null;
      slug: string | null;
      videoPlaybackId: string | null;
    }> | null;
  } | {
    _type: "contactBlock";
  } | {
    _type: "heroBlock";
    heading: string | null;
    subheading: string | null;
    videoPlaybackId: string | null;
  }> | null;
} | null;
// Variable: caseStudiesQuery
// Query: *[_type == "caseStudy"] | order(title asc) {    title,    "slug": slug.current,    client  }
export type CaseStudiesQueryResult = Array<{
  title: string | null;
  slug: string | null;
  client: string | null;
}>;
// Variable: caseStudyBySlugQuery
// Query: *[_type == "caseStudy" && slug.current == $slug][0] {    title,    "slug": slug.current,    client,    year,    industry,    deliverables,    creativeCollective,    primaryColor,    secondaryColor,    "heroVideoPlaybackId": heroVideo.asset->playbackId,    body[]{      _type,      _key,      theme,      eyebrow,      _type == "highlightsSection" => {        statement,        stats[]{ _key, value, label }      },      _type == "textSection" => {        body      },      _type == "mediaSection" => {        layout,        text,        media[]{          _type,          _key,          _type == "mux.video" => {            "playbackId": asset->playbackId          },          _type == "image" => {            "url": asset->url,            "width": asset->metadata.dimensions.width,            "height": asset->metadata.dimensions.height,            "alt": asset->altText          }        }      },      _type == "statsSection" => {        stats[]{ _key, value, label }      }    }  }
export type CaseStudyBySlugQueryResult = {
  title: string | null;
  slug: string | null;
  client: string | null;
  year: string | null;
  industry: string | null;
  deliverables: string | null;
  creativeCollective: string | null;
  primaryColor: string | null;
  secondaryColor: string | null;
  heroVideoPlaybackId: string | null;
  body: Array<{
    _type: "highlightsSection";
    _key: string;
    theme: "dark" | "light" | "primary" | "secondary" | null;
    eyebrow: string | null;
    statement: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    stats: Array<{
      _key: string;
      value: string | null;
      label: string | null;
    }> | null;
  } | {
    _type: "mediaSection";
    _key: string;
    theme: "dark" | "light" | "primary" | "secondary" | null;
    eyebrow: string | null;
    layout: "fullBleed16x9" | "pairedSquare" | "textAndMedia" | null;
    text: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    media: Array<{
      _type: "image";
      _key: string;
      url: string | null;
      width: number | null;
      height: number | null;
      alt: string | null;
    } | {
      _type: "mux.video";
      _key: string;
      playbackId: string | null;
    }> | null;
  } | {
    _type: "statsSection";
    _key: string;
    theme: "dark" | "light" | "primary" | "secondary" | null;
    eyebrow: string | null;
    stats: Array<{
      _key: string;
      value: string | null;
      label: string | null;
    }> | null;
  } | {
    _type: "textSection";
    _key: string;
    theme: "dark" | "light" | "primary" | "secondary" | null;
    eyebrow: string | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"homepage\"][0]{\n    sections[]{\n      _type,\n      _type == \"heroBlock\" => {\n        heading,\n        subheading,\n        \"videoPlaybackId\": video.asset->playbackId\n      },\n      _type == \"capesBlock\" => {\n        headline,\n        capabilities[]->{\n          title,\n          \"slug\": slug.current,\n          \"videoPlaybackId\": video.asset->playbackId\n        }\n      },\n      _type == \"contactBlock\" => {\n        _type\n      }\n    }\n  }\n": HomepageQueryResult;
    "\n  *[_type == \"caseStudy\"] | order(title asc) {\n    title,\n    \"slug\": slug.current,\n    client\n  }\n": CaseStudiesQueryResult;
    "\n  *[_type == \"caseStudy\" && slug.current == $slug][0] {\n    title,\n    \"slug\": slug.current,\n    client,\n    year,\n    industry,\n    deliverables,\n    creativeCollective,\n    primaryColor,\n    secondaryColor,\n    \"heroVideoPlaybackId\": heroVideo.asset->playbackId,\n    body[]{\n      _type,\n      _key,\n      theme,\n      eyebrow,\n      _type == \"highlightsSection\" => {\n        statement,\n        stats[]{ _key, value, label }\n      },\n      _type == \"textSection\" => {\n        body\n      },\n      _type == \"mediaSection\" => {\n        layout,\n        text,\n        media[]{\n          _type,\n          _key,\n          _type == \"mux.video\" => {\n            \"playbackId\": asset->playbackId\n          },\n          _type == \"image\" => {\n            \"url\": asset->url,\n            \"width\": asset->metadata.dimensions.width,\n            \"height\": asset->metadata.dimensions.height,\n            \"alt\": asset->altText\n          }\n        }\n      },\n      _type == \"statsSection\" => {\n        stats[]{ _key, value, label }\n      }\n    }\n  }\n": CaseStudyBySlugQueryResult;
  }
}
