import {readFileSync} from 'node:fs'
import {describe, expect, it} from 'vitest'

const source = readFileSync(new URL('./tokens.css', import.meta.url), 'utf8')

// Fluid ramps from docs/css-standardization-spec.md. Every fluid token is
// generated by one of these two helpers, so all steps share an identical
// curve shape; this test re-derives each token value from the formula so a
// hand-edited clamp can't drift from the shared ramp.
const fmt = (n: number) => String(Number(n.toFixed(2)))

/** Display type ramp: floor at a 360px viewport, cap at 1440px, then plateau. */
const typeClamp = (floorPx: number, capPx: number) => {
  const b = (capPx - floorPx) / 10.8 // 1440 − 360, in 100vw units
  const a = floorPx - (capPx - floorPx) / 3 // 360/1080
  return `clamp(${fmt(floorPx)}px, ${fmt(a)}px + ${fmt(b)}vw, ${fmt(capPx)}px)`
}

/** Vertical-rhythm ramp: floor at a 768px viewport, cap at 1440px. */
const spaceClamp = (floorPx: number, capPx: number) => {
  const b = (capPx - floorPx) / 6.72 // 1440 − 768, in 100vw units
  const a = floorPx - ((capPx - floorPx) * 768) / 672
  return `clamp(${fmt(floorPx)}px, ${fmt(a)}px + ${fmt(b)}vw, ${fmt(capPx)}px)`
}

describe('fluid type tokens (spec §3)', () => {
  it.each([
    ['--type-h1', 64, 200],
    ['--type-h2', 48, 140],
    ['--type-h3', 40, 120],
    ['--type-h4', 40, 80],
    ['--type-h5', 32, 56],
    ['--type-section-heading', 32, 56],
  ] as const)('%s rides the shared 360→1440 ramp (%s→%s)', (token, floor, cap) => {
    expect(source).toContain(`${token}: ${typeClamp(floor, cap)};`)
  })

  it('marquee rides the shared ramp with the floor held at 80', () => {
    expect(source).toContain(`--type-marquee: ${typeClamp(80, 200)};`)
  })
})

describe('fluid spacing tokens (spec §4)', () => {
  it.each([
    ['--space-2xl', 80, 120],
    ['--space-3xl', 96, 160],
    ['--space-4xl', 120, 200],
  ] as const)('%s rides the shared 768→1440 ramp (%s→%s)', (token, floor, cap) => {
    expect(source).toContain(`${token}: ${spaceClamp(floor, cap)};`)
  })

  it('keeps 96px and below fixed so component spacing stays put', () => {
    for (const token of ['xs-4', '3xs', '16', '2xs', 'xs', 's', 'm', 'l', 'xl']) {
      expect(source).toMatch(new RegExp(`--space-${token}: \\d+px;`))
    }
  })
})

describe('Uno shortcut wiring', () => {
  const unoConfig = readFileSync(new URL('../../uno.config.ts', import.meta.url), 'utf8')

  // Bare `text-[var(--x)]` is ambiguous in Uno and emits a color declaration
  // instead of font-size; the length: hint is what makes the ramp apply.
  it.each(['h1', 'h2', 'h3', 'h4', 'h5', 'section-heading'])(
    'type-%s references its token with the length: hint',
    (step) => {
      expect(unoConfig).toContain(`text-[length:var(--type-${step})]`)
    },
  )
})

describe('canonical breakpoints (spec §5)', () => {
  it('defines each boundary once as a custom media', () => {
    expect(source).toContain('@custom-media --bp-small (max-width: 767.98px);')
    expect(source).toContain('@custom-media --bp-below-desktop (max-width: 1023.98px);')
    expect(source).toContain('@custom-media --bp-desktop (min-width: 1024px);')
    expect(source).toContain('@custom-media --bp-600 (max-width: 599.98px);')
    expect(source).toContain('@custom-media --bp-960 (max-width: 959.98px);')
  })
})
