export { MOTION, EASE, STAGGER, SCROLL, POINTER, REDUCED_MOTION_QUERY, reducedMotionQuery, prefersReducedMotion } from './config';
export { splitText, type SplitHandle, type SplitUnit } from './splitText';
export { revealText, type RevealOptions, type RevealHandle } from './reveal';
export { initPressFeedback } from './hover';
export { LoadingSurface, type LoadingPhase, type LoadingSurfaceOptions } from './loading';
export { initRouteTransition, ROUTE_REVEALED_EVENT, type RouteTransitionOptions } from './routeTransition';
export { initPinnedStory, type PinnedStoryOptions } from './pinnedStory';
export { initSmoothScroll, getLenis } from './smoothScroll';
export { initDepthLayer } from './depthLayer';
export { initHorizontalRail, type HorizontalRailHandle } from './horizontalRail';
export { initMotion } from './bootstrap';
